"""empty message

Revision ID: 2363bdc6bec8
Revises: c1eb9ba929bf
Create Date: 2025-01-05 19:28:27.845134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2363bdc6bec8'
down_revision = 'c1eb9ba929bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_bp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounterid', sa.Integer(), nullable=False),
    sa.Column('sysbp', sa.Integer(), nullable=True),
    sa.Column('diabp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['encounterid'], ['encounter.encounterid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('encounter_bp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_encounter_bp_encounterid'), ['encounterid'], unique=False)

    with op.batch_alter_table('bp', schema=None) as batch_op:
        batch_op.drop_index('ix_bp_enterpriseid')

    op.drop_table('bp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enterpriseid', sa.INTEGER(), nullable=False),
    sa.Column('bpdate', sa.DATE(), nullable=False),
    sa.Column('sysbp', sa.INTEGER(), nullable=True),
    sa.Column('diabp', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['enterpriseid'], ['patient.enterpriseid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bp', schema=None) as batch_op:
        batch_op.create_index('ix_bp_enterpriseid', ['enterpriseid'], unique=False)

    with op.batch_alter_table('encounter_bp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_encounter_bp_encounterid'))

    op.drop_table('encounter_bp')
    # ### end Alembic commands ###
