"""empty message

Revision ID: b5a020efa1e7
Revises: 2363bdc6bec8
Create Date: 2025-01-15 08:57:43.399429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5a020efa1e7'
down_revision = '2363bdc6bec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mammogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterpriseid', sa.Integer(), nullable=False),
    sa.Column('mammo_date', sa.Date(), nullable=False),
    sa.Column('mammo_modified_date', sa.Date(), nullable=False),
    sa.Column('mammo_result', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['enterpriseid'], ['patient.enterpriseid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mammogram', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mammogram_enterpriseid'), ['enterpriseid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mammogram', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mammogram_enterpriseid'))

    op.drop_table('mammogram')
    # ### end Alembic commands ###
